"""mailer: campaign options and send log snapshot

Revision ID: 545b5112f7f5
Revises: d215c95c18ae
Create Date: 2026-10-01 11:46:12.809729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545b5112f7f5'
down_revision: Union[str, None] = 'd215c95c18ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('allow_guessed_emails', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('send_log', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('send_log', sa.Column('subject', sa.String(length=500), nullable=True))
    op.add_column('send_log', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('send_log', sa.Column('error', sa.Text(), nullable=True))
    op.create_index('ix_send_log_email', 'send_log', ['email'], unique=False)
    # ### end Alembic commands ###
    # Autogenerate nie wykrywa nowych wartości enumów. SQLAlchemy trzyma w bazie NAZWY członków enuma.
    op.execute("ALTER TYPE send_status ADD VALUE IF NOT EXISTS 'SKIPPED'")


def downgrade() -> None:
    # Postgres nie pozwala usunąć wartości z typu enum -- 'SKIPPED' zostaje w send_status.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_send_log_email', table_name='send_log')
    op.drop_column('send_log', 'error')
    op.drop_column('send_log', 'body')
    op.drop_column('send_log', 'subject')
    op.drop_column('send_log', 'email')
    op.drop_column('campaigns', 'allow_guessed_emails')
    # ### end Alembic commands ###
