"""enrichment: score explanation and enriched_at

Revision ID: 54de493c4b9e
Revises: 1f19c9cca81e
Create Date: 2026-09-30 21:45:14.387047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54de493c4b9e'
down_revision: Union[str, None] = '1f19c9cca81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('score_explanation', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'enriched_at')
    op.drop_column('companies', 'score_explanation')
    # ### end Alembic commands ###
