"""runs history and company exclusion

Revision ID: d215c95c18ae
Revises: 54de493c4b9e
Create Date: 2026-10-01 11:17:33.844049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd215c95c18ae'
down_revision: Union[str, None] = '54de493c4b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('DISCOVERY', 'ENRICHMENT', name='run_kind'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_created_at', 'runs', ['created_at'], unique=False)
    op.add_column('companies', sa.Column('excluded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'excluded_at')
    op.drop_index('ix_runs_created_at', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
